export const styles: Record<string, React.CSSProperties> = {
  container: {
    width: "100%",
    minHeight: "100vh",
    fontFamily: "Arial, sans-serif",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: "60px",
    boxSizing: "border-box",
    backgroundColor: "#fff",
  },
  logo: {
    marginBottom: "40px",
    fontSize: "2rem",
    fontWeight: 400,
  },
  searchBox: {
    position: "relative",
    width: "80%",
    maxWidth: "600px",
    borderRadius: "50px",
    border: "1px solid #dfe1e5",
    display: "flex",
    alignItems: "center",
    padding: "0 15px",
    backgroundColor: "#fff",
    boxShadow: "0 1px 2px rgba(0,0,0,0.1)",
  },
  searchIcon: {
    marginRight: "8px",
    fontSize: "1.2rem",
    color: "#9aa0a6",
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    fontSize: "1rem",
    padding: "12px 0",
  },
  clearIcon: {
    cursor: "pointer",
    marginRight: "8px",
    fontSize: "1.2rem",
    color: "red",
  },
  microphoneIcon: {
    cursor: "pointer",
    fontSize: "1.2rem",
    color: "#9aa0a6",
  },
  suggestions: {
    position: "absolute",
    top: "55px",
    left: 0,
    right: 0,
    border: "1px solid #dfe1e5",
    borderTop: "none",
    borderRadius: "0 0 24px 24px",
    backgroundColor: "#fff",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    zIndex: 1000,
    maxHeight: "300px",
    overflowY: "auto",
  },
  suggestionItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: "10px 20px",
    fontSize: "0.95rem",
    cursor: "pointer",
    borderBottom: "1px solid #f1f1f1",
    textAlign: "left",
  },
  removeHistoryBtn: {
    marginLeft: "10px",
    background: "none",
    border: "none",
    color: "grey",
    cursor: "pointer",
  },
  metadata: {
    width: "80%",
    maxWidth: "600px",
    marginTop: "20px",
    textAlign: "left",
  },
  results: {
    width: "80%",
    maxWidth: "600px",
    marginTop: "10px",
    marginBottom: "60px",
  },
  resultItem: {
    marginBottom: "20px",
  },
  resultTitle: {
    textDecoration: "none",
    color: "#1a0dab",
    fontSize: "1.1rem",
    display: "block",
    marginBottom: "4px",
  },
  resultDescription: {
    fontSize: "0.95rem",
    color: "#4d5156",
    margin: 0,
  },
};
